### ISSUE TITLE
[Ошибка]

### ISSUE THREAD

**Issue by egordoronchenko** [Bayselonarrend/OpenIntegrations#12]
**Описание ошибки**
При отправке поста для группы в вк выскакивает ошибка
![image](https://github.com/Bayselonarrend/OpenIntegrations/assets/138254184/bc691a37-dbe5-4147-a862-5528b9e5e478)

**Воспроизведение**
При вызове метода OPI_VK.СоздатьПост передаются стандартные настройки аутентификации, текст, картинки в виде двоичных данных 9 штук.
дополнительно используется функционал отложенного постинга так же передается в параметрах
пост все таки уходит с 3-5 попытки.

**Comment by Bayselonarrend** [comment]
> пост все таки уходит с 3-5 попытки

Если пост все таки создается, просто не с первого раза, значит при одних и тех же данных VK возвращает разный ответ - иногда некорректный. 

Судя по ошибке, проблема возникает при загрузке какой-то из 9 фотографий - на одну из них (не обязательно одну и ту же каждый раз) сервер возвращает некорректный ответ. Нужно в отладке поставить Останавливать по ошибке и посмотреть, что находится в переменной Ответ, из которой тянется hash. 

Если там будет тип не соответствие, а ДвоичныеДанные, то дополнительно через вычислить надо посмотреть ПолучитьСтрокуИзДвоичныхДанных(Ответ). Я сам такую ошибку не ловил, но возможно слишком быстро отправляются запросы на загрузку фото и в строке ответа будет что-нибудь вроде Too Many Requests. Если подтвердится - добавлю паузу в фиксе

**Comment by egordoronchenko** [comment]
в ПолучитьСтрокуИзДвоичныхДанных(Ответ)  такие данные 
![image](https://github.com/Bayselonarrend/OpenIntegrations/assets/138254184/6054fe26-b184-4de2-9ca9-a3e48a9afcf6)


Служебные сообщения высветившиеся при остановке по ошибке
Ошибка при вызове метода контекста (ПрочитатьJSON)
{ОбщийМодуль.OPI_Инструменты.Модуль(158)}:    Данные = ПрочитатьJSON(ЧтениеJSON, Истина, Неопределено, ФорматДатыJSON.ISO);
{ОбщийМодуль.OPI_Инструменты.Модуль(510)}:            Ответ = JsonВСтруктуру(Ответ);
{ОбщийМодуль.OPI_Инструменты.Модуль(401)}:        ОбработатьОтвет(Ответ);      
{ОбщийМодуль.OPI_Инструменты.Модуль(73)}:    Возврат ВыполнитьЗапросМультипарт(URL, "POST", Параметры, Файлы, ТипКонтента, ДопЗаголовки);
{ОбщийМодуль.OPI_VK.Модуль(1747)}:    Ответ = OPI_Инструменты.PostMultipart(URL, Параметры, Файлы);
{ОбщийМодуль.OPI_VK.Модуль(1672)}:	Ответ       = ЗагрузитьФотоНаСервер(Картинка, Параметры, Вид);   
{ОбщийМодуль.OPI_VK.Модуль(98)}:        ОтветСоответствие = ПолучитьСоответствиеКартинки(КартинкаПоста, Параметры_, "Пост");
{ВнешняяОбработка.ОтправитьВВК.МодульОбъекта(87)}:	Ответ = OPI_VK.СоздатьПост(ТекстПоста,ФайлыДД,,,ПараметрыПодключения);
{ВнешняяОбработка.ОтправитьВВК.МодульОбъекта(60)}:        ОтправитьВВКНаСервере();
{ВнешняяОбработка.ОтправитьВВК.Форма.Форма.Форма(13)}:    Об.ВыполнитьКоманду(); 
по причине:
Непредвиденный символ при чтении JSON
Поле объекта не обнаружено (hash)
{ОбщийМодуль.OPI_VK.Модуль(1943)}:        Параметры.Вставить(Hash, Ответ[Hash]);
{ОбщийМодуль.OPI_VK.Модуль(1748)}:    ЗаполнитьПараметрыЗагрузкиФото(Метод, Ответ, Параметры);
{ОбщийМодуль.OPI_VK.Модуль(1672)}:	Ответ       = ЗагрузитьФотоНаСервер(Картинка, Параметры, Вид);   
{ОбщийМодуль.OPI_VK.Модуль(98)}:        ОтветСоответствие = ПолучитьСоответствиеКартинки(КартинкаПоста, Параметры_, "Пост");
{ВнешняяОбработка.ОтправитьВВК.МодульОбъекта(87)}:	Ответ = OPI_VK.СоздатьПост(ТекстПоста,ФайлыДД,,,ПараметрыПодключения);
{ВнешняяОбработка.ОтправитьВВК.МодульОбъекта(60)}:        ОтправитьВВКНаСервере();
{ВнешняяОбработка.ОтправитьВВК.Форма.Форма.Форма(13)}:    Об.ВыполнитьКоманду();

**Comment by Bayselonarrend** [comment]
А картинки двоичные или пути к файлам?

**Comment by egordoronchenko** [comment]
Двоичные данные

**Comment by Bayselonarrend** [comment]
Какие то странные вещи от VK - он сам присылает URL, куда грузить фотографии, но иногда они нормальные, а иногда - 404. При том что и те и те - одного формата, только UIDы меняются

![image](https://github.com/Bayselonarrend/OpenIntegrations/assets/105596284/20ac847e-ceba-4f09-9af4-651520c21685)

![image](https://github.com/Bayselonarrend/OpenIntegrations/assets/105596284/4a244e20-9521-4f0e-bcdc-30ca6c48b1da)
![image](https://github.com/Bayselonarrend/OpenIntegrations/assets/105596284/a2e513ca-9058-45e0-b1cf-9931a140102b)

Все что я могу тут сделать - добавить несколько попыток в цикле на загрузку фото (помогает). У меня уже помимо этого есть несколько изменений, так что через пол часа - час выкачу новый релиз.

**Comment by egordoronchenko** [comment]
Хорошо. Спасибо!
