### ISSUE TITLE
[Вопрос]

### ISSUE THREAD

**Issue by egordoronchenko** [Bayselonarrend/OpenIntegrations#13]
Еще раз здравствуйте
может быть знаете какой параметр требуется отправлять чтобы сообщение было отложеным в телеграмм?
или для ботов данный функционал у телеграм не реализован?

**Comment by Bayselonarrend** [comment]
Вроде нет такого в API. Да и в целом, на мой субъективный взгляд, куда лучше сделать регистр с сообщениями и датой их публикаций. Обходить их регламентным там. Куда более гибко, даже если бы такой функционал был.

Если интересно, есть старый проект [2athenaeum](https://github.com/Bayselonarrend/2athenaeum). Из него произошел Открытый пакет интеграций. Там местами узкозаточенная, но вполне себе CMS для паблика вк и телеграм канала

**Comment by egordoronchenko** [comment]
Регзадание не подойдет к сожалению. 1ска будет запускаться 1-2 раза в день в лучшем случае и не серверная. Чисто разобрать предложенные сообщения чтобы запостить их в вк (отложено это реализовать получилось) ну а с телегой тогда обойдутся :)

Спасибо вам! И хороших выходных!
