### ISSUE TITLE
[Предложение] Добавить параметр parse_mode в TG

### ISSUE THREAD

**Issue by nicklyjack** [Bayselonarrend/OpenIntegrations#14]
**Существующая проблема**
Столкнулся с проблемой использования разных языков разметки при отправке в Telegram. Иногда я использую Markdown, а иногда HTML. К сожалению, при использовании вашей библиотеки нельзя указать, какой тип разметки использовать. По умолчанию всегда используется Markdown.

**Пути решения**
Добавить дополнительный параметр при вызове методов SendMessage, SendDocument и т.д. По умолчанию он будет иметь значение «Markdown», но также будет возможность указать его явно при вызове. 

**Альтернативы**
Опишите возможные альтернативы в решении вопроса, если таковые возможны

**Дополнительная информация**
Огромная благодарность за Ваши труды. Нереально крутой проект :)

**Comment by Bayselonarrend** [comment]
Здравствуйте. Можно добавить, да. Напишу здесь, когда сделаю - думаю, это не займет много времени

> Огромная благодарность за Ваши труды. Нереально крутой проект :)

Спасибо, мне приятно)

**Comment by Bayselonarrend** [comment]
Добавил, но новый релиз пока не буду делать. Можете просто скопировать себе новый текст модуля 

[https://github.com/Bayselonarrend/OpenIntegrations/blob/main/OPI/src/CommonModules/OPI_Telegram/Module.bsl](https://github.com/Bayselonarrend/OpenIntegrations/blob/main/OPI/src/CommonModules/OPI_Telegram/Module.bsl)

**Comment by nicklyjack** [comment]
Супер!

Спасибо большое!
