### ISSUE TITLE
Файл ~8 гб не появляется в google drive

### ISSUE THREAD

**Issue by podkin** [Bayselonarrend/OpenIntegrations#15]
**Описание ошибки**
Загрузка идёт(скриншот) но по итогу файл в google drive не появляется. Хотя маленький файл загружается без проблем и я его вижу в google.

**Ожидаемое поведение**
Файл должен появится в Google drive

**Скриншоты**
![image](https://github.com/Bayselonarrend/OpenIntegrations/assets/61511308/148678ef-7f48-4374-b94d-7773146b12da)

**Платформа и конфигурация**
OneScript версия

**Comment by Bayselonarrend** [comment]
Видимо проблема все таки не в MIME - попробовал загрузить, загрузилось. Попробуйте сделать вот так и посмотреть, что в ответе будет

```bsl
Ответ = OPI_GoogleDrive.ЗагрузитьФайл(Токен, Файл, Описание);
Сообщить(OPI_Инструменты.JSONСтрокой(Ответ));
```

Можно взять файл меньше, если есть другой bak. > 256 МБ уже считается большой файл

**Comment by podkin** [comment]
На квоту ругается всё таки.
![image](https://github.com/Bayselonarrend/OpenIntegrations/assets/61511308/3728accb-2298-4012-8841-6edc8410e437)

**Comment by podkin** [comment]
Нашёл что нужно трансформировать аккаунт Google API. https://stackoverflow.com/questions/40535355/how-to-fix-the-storage-exceeded-issue-for-google-drive-when-uploading-using-serv

**Comment by Bayselonarrend** [comment]
По этому вопросу все тогда, получается?

**Comment by podkin** [comment]
Да, буду разбираться со статьей, спасибо, большое за помощь!

**Comment by Bayselonarrend** [comment]
Отлично. закрываю тогда

Можете поставить :star: , будете тогда узнавать об обновлениях
