### ISSUE TITLE
[Предложение] Вынести Oscript Версию в отдельный репо

### ISSUE THREAD

**Issue by Segate-ekb** [Bayselonarrend/OpenIntegrations#17]
**Существующая проблема**
Это даже и не проблема, а так... мысли вслух... 

У меня есть желание поконтрибьютить в версию для оскрипт. При этом я не готов тащить обратную совместимость в 1с. 

**Пути решения**
Может стоит подумать о разделении проектов, как это сделано в том же коннекторе...

**Comment by Bayselonarrend** [comment]
Нет, этого не будет. Версия для 1С - первична и на ее основе автоматически в Github Actions создается версия для OS и CLI. В них вообще ничего не пишется руками.

Это принципиальный вопрос, так как, на мой взгляд, разделение версий может привести лишь к тому, что одна из них (скорее всего для OS как менее популярная) просто отстанет и зачахнет из-за нехватки времени и нарастающих различий в коде, которые невозможно будет смерджить ни в ту, ни в обратную сторону. Особенно если в OneScript буду использоваться вещи, недоступные в 1С, в чем, как я понимаю, и смысл.
