### ISSUE TITLE
[Вопрос] OPI_Telegram - вопросы разметки

### ISSUE THREAD

**Issue by mrtwister** [Bayselonarrend/OpenIntegrations#18]
Вопрос по режиму парсинга по умолчанию.
Подскажите пожалуйста, не считаете ли вы правильнее по умолчанию использовать "MarkdownV2" так как он по умолчанию используется в примерах документации(смотрел здесь). Разметку с режимом "Markdown" я так и не смог заставить работать исходя из примеров документации.

**Comment by Bayselonarrend** [comment]
Я исхожу из того, что она все время стояла Markdown и теперь сохраняется обратная совместимость))

**Comment by Bayselonarrend** [comment]
В предыдущих версиях она захардкожена была просто, не было параметра

**Comment by mrtwister** [comment]
> Я исхожу из того, что она все время стояла Markdown и теперь сохраняется обратная совместимость))
Понятно, возможно стоит перейти на простой текст по умолчанию? Чтобы ничего не сломалось(максимум придет нераскрашенное сообщение) и по умолчанию все работало так как и должно - какой текст отправил такой и пришел.

**Comment by mrtwister** [comment]
Еще может быть стоит добавить функцию для экранирования текста если режим парсинга"MarkdownV2" в служебный модуль. Могу прислать в пулреквест(наверно)

**Comment by Bayselonarrend** [comment]
Тогда при обновлении до новой версии у старых пользователей полетит разметка, если они не использовали этот параметр (или его тогда вообще не было)

**Comment by Bayselonarrend** [comment]
>Еще может быть стоит добавить функцию для экранирования текста если режим парсинга"MarkdownV2" в служебный модуль. Могу прислать в пулреквест(наверно)

Я думаю, хорошей идей было бы добавить параметр Разметка в процедуру ЗаменаСпецсимволов и от нее играть: какая разметка - такое экранирование

**Comment by Bayselonarrend** [comment]
Могу сам заняться, могу подождать PR

**Comment by mrtwister** [comment]
> Могу сам заняться, могу подождать PR
Если не найдется кому починить, попробую до конца недели пройти полный путь. Взять EDT, пустую конфигурацию, вытащить, сделать правки, собрать, проверить. что ничего не сломал, предложить PR.

**Comment by Bayselonarrend** [comment]
> > Могу сам заняться, могу подождать PR
> 
> 
> 
> Если не найдется кому починить, попробую до конца недели пройти полный путь. Взять EDT, пустую конфигурацию, вытащить, сделать правки, собрать, проверить. что ничего не сломал, предложить PR. Тогда получается, что в самой функции не надо экранировать ничего(в случае с "MarkdownV2" некоторые символы надо экранировать) иначе отправка в формате HTML теряет смысл (разметка будет экранирована)

& наверное надо экранировать

**Comment by Bayselonarrend** [comment]
[https://github.com/Bayselonarrend/OpenIntegrations/pull/21](https://github.com/Bayselonarrend/OpenIntegrations/pull/21)
