### ISSUE TITLE
[Вопрос] Замена спецсимволов

### ISSUE THREAD

**Issue by mrtwister** [Bayselonarrend/OpenIntegrations#19]
Замена спецсимволов при отправке сообщения. Подскажите пожалуйста какую функцию она несет? Так и не смог понять. Если ее отключить то сообщения хорошо уходят как с экранированием символов так и без них.

**Comment by Bayselonarrend** [comment]
Хороший вопрос - она очень старая. Посмотрю.

**Comment by Bayselonarrend** [comment]
Короче, это из каких-то дремучих времен библиотеки, из которой произошел ОПИ , где разметкой по умолчанию был HTML. Переработаю эту процедуру, спасибо
