### ISSUE TITLE
Добавить подсистему для объединения с текущим расширением

### ISSUE THREAD

**Issue by malikov-pro** [Bayselonarrend/OpenIntegrations#22]
**Существующая проблема**
При объединении с текущим расширением желательно выделить модули в отдельную подсистему

**Пути решения**
Добавить подсистему, добавить в её состав модули

**Comment by Bayselonarrend** [comment]
https://github.com/Bayselonarrend/OpenIntegrations/commit/a530e33e0e2d7c8cf32ea49b52d843263bf82293
