### ISSUE TITLE
[Предложение] Расширенное формирование клавиатуры

### ISSUE THREAD

**Issue by mrtwister** [Bayselonarrend/OpenIntegrations#25]
**Существующая проблема**
На текущий момент, нет возможности сформировать клавиатуру с произвольным количеством кнопок в каждой строке

**Пути решения**
Предлагаю добавить метод который позволит формировать клавиатуру произвольно. Не только в ряд или столбиком. А сделать столько строк и столько кнопок в каждой строке, сколько нужно. Путем вложения в массив означающий строки массива означающий кнопки. Также возможно необходимо дать программисту возможность переопределять параметр кабека, если это необходимо

**Comment by Bayselonarrend** [comment]
Ну, метод формирования клавиатуры - это скорее пример самого простого варианта. Функция отправки сообщений принимает готовую сформированную клавиатуру -> под свои нужды её можно формировать любой, какой пользователю придет в голову в конкретный момент. 

Просто думаю, что если понадобится нечто более сложное, нежели есть сейчас, то лучше это и отдать на откуп пользователю, потому что все хотелки все равно не предусмотришь

**Comment by mrtwister** [comment]
Да там кроме вышеперечисленного то, собственно больше и добавить то нечего.

**Comment by Bayselonarrend** [comment]
>Да там кроме вышеперечисленного то, собственно больше и добавить то нечего.

Если я не ошибаюсь, то на каждую кнопку свой колбэк можно повесить

Наверное пока нет, потому что тут больше вопросов, чем потенциальной пользы

1. Старую функцию не заменишь, не будет обратной совместимости
2. Если пользователь сделает массив массивов и выберет колбэк, то, собственно, чегоб еще в структуру тогда сразу не засунуть - вот тебе и клавиатура. Кто-то в комментах на ИФ интересовался колбэками и кастомной клавой - вроде никахи проблем с этим не возникло
3. А главное - я не знаю, как распрасить массив массивов в CLI версии))

**Comment by mrtwister** [comment]
Хорошо. Тогда я просто оставлю это здесь. 

```bsl
Функция СформироватьКлавиатуруПоМассивуКнопок(Знач МассивКнопок
    , Знач ПодСообщением = Ложь
    , Знач ОднаПодОдной = Истина) Экспорт

	Если ОднаПодОдной Тогда

		Строки = Новый Массив;

		Для Каждого Кнопка Из МассивКнопок Цикл
			Кнопки = Новый Массив;
			Кнопка = OPI_Инструменты.ЧислоВСтроку(Кнопка);
			Кнопки.Добавить(Новый Структура("text,callback_data", Кнопка, Кнопка));
			Строки.Добавить(Кнопки);
		КонецЦикла;

	Иначе

		Строки = Новый Массив;
		Кнопки = Новый Массив;

		Для Каждого Кнопка Из МассивКнопок Цикл
			Кнопка = OPI_Инструменты.ЧислоВСтроку(Кнопка);
			Кнопки.Добавить(Новый Структура("text,callback_data", Кнопка, Кнопка));
		КонецЦикла;

		Строки.Добавить(Кнопки);
	КонецЕсли;

	Если ПодСообщением Тогда
		СтруктураПараметра = Новый Структура("inline_keyboard,rows", Строки, 1);
	Иначе
		СтруктураПараметра = Новый Структура("keyboard,resize_keyboard", Строки, Истина);
	КонецЕсли;

	ЗаписьJSON    = Новый ЗаписьJSON;
	ПЗJSON        = Новый ПараметрыЗаписиJSON(ПереносСтрокJSON.Нет, , , ЭкранированиеСимволовJSON.СимволыВнеASCII);
	ЗаписьJSON.УстановитьСтроку(ПЗJSON);

	ЗаписатьJSON(ЗаписьJSON, СтруктураПараметра);

	Возврат ЗаписьJSON.Закрыть();

КонецФункции
```
