### ISSUE TITLE
[Предложение] Добавить метод удаления сообщения

### ISSUE THREAD

**Issue by mrtwister** [Bayselonarrend/OpenIntegrations#26]
**Существующая проблема**
На текущий момент удаление поста не поддерживается

**Пути решения**
Предлагаю добавить метод удаления поста, но не придумал в какую область этот метод можно было бы поместить, в "Прочее"?

**Comment by Bayselonarrend** [comment]
А это про какой API?

**Comment by mrtwister** [comment]
Оу сорян. Речь про api телеги

**Comment by Bayselonarrend** [comment]
Думаю в администрирование нормально будет

**Comment by Bayselonarrend** [comment]
https://github.com/Bayselonarrend/OpenIntegrations/pull/28
