### ISSUE TITLE
[Предложение] Установка oint-cli с использованием opm.

### ISSUE THREAD

**Issue by arkuznetsov** [Bayselonarrend/OpenIntegrations#32]
Хотелось бы иметь возможность установить oint-cli как обычное приложение с помощью `opm install`.

**Comment by arkuznetsov** [comment]
да, конечно, например gitsync, cpdb, yard и т.п.
я понимаю, что была идея сделать все в 1-м exe-шнике, но это не всегда удобно, бьывает что нужно и установить "в исхожниках" в основной каталог библиотек.
я ручками то смог так поставить, просто из архива исходников скопировав.

**Comment by Bayselonarrend** [comment]
Ну, просто oint-cli это буквально тот же oint, только с хэлпом и приемников для ввода параметров из консоли. Можно конечно сделать его пакетом тоже, но я думал, что если его надо откуда-то еще использовать, то проще обычный oint, нет?

**Comment by Bayselonarrend** [comment]
Или это типо чтобы делать `oscript oint-cli ...` ?

**Comment by arkuznetsov** [comment]
Ну вот смотри, что я сделал:
- Скачал исходники
- Вытащил из них src\ru\cli и положил в C:\Program Files\OneScript\lib\oint-cli
- В C:\Program Files\OneScript\bin сделал батничек oint.bat с содержимым
```bat
@call oscript "C:\Program Files\OneScript\lib\oint-cli\core\Classes\Приложение.os" %*
@exit /b %ERRORLEVEL%
```
Все, теперь я могу использовать как приложение.

Хотелось бы, чтобы можно было то же самое сделать командой вроде `opm install oint-cli`

**Comment by Bayselonarrend** [comment]
Ну, можно сделать да, посмотрю. Хотя чем это лучше exe я все равно не очень понимаю)

**Comment by arkuznetsov** [comment]
Для всякой "ДевОпсины" минимизация количества инструментов, в данном случае способов установки - большое благо.

**Comment by Bayselonarrend** [comment]
Ок, сделаю пакет

**Comment by arkuznetsov** [comment]
oint - библиотека
oint-cli - то что я хочу дергать из пайплайна!

**Comment by Bayselonarrend** [comment]
https://github.com/oscript-library/oint-cli
