### ISSUE TITLE
[Предложение] Bitrix24: Добавить методы работы с подразделениями

### ISSUE THREAD

**Issue by alei1180** [Bayselonarrend/OpenIntegrations#34]
**Пути решения**
https://dev.1c-bitrix.ru/rest_help/departments/index.php

**Comment by Bayselonarrend** [comment]
Да, есть такое в планах
https://github.com/users/Bayselonarrend/projects/4

**Comment by Bayselonarrend** [comment]
https://github.com/Bayselonarrend/OpenIntegrations/releases/tag/1.11.1
