### ISSUE TITLE
[Ошибка] Некорректная обработка initData для TMA

### ISSUE THREAD

**Issue by proDOOMman** [Bayselonarrend/OpenIntegrations#40]
Заметил ошибку в функции OPI_Telegram.ОбработатьДанныеTMA. Преобразование строки данных в соответствие будет некорректным, если например в имени пользователя будет содержаться символ "&".

Чтобы этого избежать, надо сначала разбивать строку на массив подстрок по разделителю "&", затем делить подстроки по разделителю "=" и только после этого использовать РаскодироватьСтроку на всех подстроках.

**Comment by Bayselonarrend** [comment]
https://github.com/Bayselonarrend/OpenIntegrations/commit/0d7123263c496ef243e50970cc9e424de7903102
