### ISSUE TITLE
Добавить поддержку хранилища S3

### ISSUE THREAD

**Issue by malikov-pro** [Bayselonarrend/OpenIntegrations#41]
В свое время делал доработку для хранения файлов https://infostart.ru/1c/tools/1276986/, но не докрутил и интерфейс был упрощенный под OpenStack.

Планирую добавить в Розница 2 РИБ (через БСП) хранение в min.io + проксирование через https://github.com/imgproxy/imgproxy

Вариант сделать транспорт совместно в виде модуля для OPI.

**Comment by Bayselonarrend** [comment]
Я не очень знаю за S3, если честно
Если расскажете подробнее, что это будет, то можно подумать

**Comment by malikov-pro** [comment]
Если кратко, то локальный аналог Google Drive, на который у вас уже есть модуль. 
По сути то что под капотом у сервисов хранения файлов.
https://yandex.cloud/ru/docs/glossary/s3

**Comment by Bayselonarrend** [comment]
Ну, а в плане, что должны покрывать методы?
> (через БСП) хранение в min.io + проксирование через https://github.com/imgproxy/imgproxy

Это будет использоваться в тех методах, что в ОПИ, или уже в Рознице?
И что от меня требуется?)

**Comment by malikov-pro** [comment]
Требуется реализовать транспорт
* Получить информацию об объекте
* Получить список каталогов
* Получить список файлов
* Загрузить файл
* Создать папку
* Скачать файл
* Скопировать объект
* Обновить файл
* Удалить объект
* Получить описание файла

Состыковка транспорта с БСП уже с меня.

**Comment by Bayselonarrend** [comment]
Эти методы с меня?

**Comment by malikov-pro** [comment]
> Эти методы с меня?

Да.
Пока у себя стенд с min.io разверну, сделаю прототип, после код передам, приведешь в порядок под свой формат. Сам использую Коннектор. Можно будет протестировать с яндексовой реализацией.

**Comment by Bayselonarrend** [comment]
Можно попробовать, если в этом прототипе что-то будет и будет возможность привести его к общему виду в разумное время. Потому что делать с нуля библиотеку под S3, честно говоря, сейчас в мои планы не входило

**Comment by malikov-pro** [comment]
Реализация https://infostart.ru/1c/articles/2033497/
У себя пока еще не прикрутил.

**Comment by Bayselonarrend** [comment]
Ну...
Я тоже читал эту статью Седайко. Статья ок, но это не то, чтобы готовая реализация - там куча БСП, работы с полями обработки и хардкода

**Comment by Bayselonarrend** [comment]
https://github.com/Bayselonarrend/OpenIntegrations/releases/tag/1.16.0
