### ISSUE TITLE
Работа с параметрами запроса Bitrix

### ISSUE THREAD

**Issue by Untru** [Bayselonarrend/OpenIntegrations#42]
**Описание ошибки**
Фильтрация в задачах битрикс. 

В документации к битрикс в Получить список задач идет пример 

    // Полную структуру фильтра можно найти в функции ПолучитьСтруктуруФильтраЗадач
    Фильтр = Новый Структура;
    Фильтр.Вставить("CREATED_BY"    , 1);
    Фильтр.Вставить("RESPONSIBLE_ID", 10);

Но для отбора, например "Больше даты" необходимо фильтр указывать типа ">CREATED_DATE", что структура не поддерживает,
Предлагаю поменять колекцию ПолучитьСтруктуруФильтраЗадач на ПолучитьСоответствиеФильтраЗадач
Так же предлагаю добавить описанеи про эту возможность, так как она не очевидна

Так же нет возможность добавить Select для фильртации полей вывода, предлагаю поддержать эту возможность.

**Comment by Untru** [comment]
Видимо надо поддержать массив из начений, так как ключи могут повторяться, например:
select[]=ID
select[]=CREATED_BY

**Comment by Bayselonarrend** [comment]
Я согласен, что стоит поменять пример получения списка задач и дописать это в какое-нибудь примечание. На счет самой функции получения структуры не уверен, потому что подобные функции ПолучитьСтруктуруЧегототам в принципе и не создавались с расчетом на прямое использование: для 1С они нужны, чтобы в их коде можно было посмотреть список полей, а для CLI - вывести json. Тот же фильтр по всем полям одновременно, которые возвращает ПолучитьСтруктуруФильтраЗадач" вряд ли кому то нужен

Необходимости select тогда не понимал и сейчас тоже: зачем ограничивать количество возвращаемых полей, если так и так это соответствие и данные достаются по ключам? На мой взгляд лишний +1 параметр, но может я чего-то не понимаю

**Comment by Bayselonarrend** [comment]
О, придумал: добавлю параметр КакСоответствие в ПолучитьСтруктуруФильтраЗадач. А то если название функции поменять то еще что-нибудь у кого-нибудь сломается после обновления)

**Comment by Untru** [comment]
> Необходимости select тогда не понимал и сейчас тоже: зачем ограничивать количество возвращаемых полей, если так и так это соответствие и данные достаются по ключам? На мой взгляд лишний +1 параметр, но может я чего-то не понимаю

Из документации:

> По умолчанию будут возвращены все невычисляемые поля основной таблицы запроса.

Мне потребовалось вытащить поле UF_CRM_TASK, оно вытаскивается только при примом его указании.

**Comment by Bayselonarrend** [comment]
Пон. Добавлю последним параметром

**Comment by Bayselonarrend** [comment]
[1.15.0](https://github.com/Bayselonarrend/OpenIntegrations/releases/tag/1.15.0)
