### ISSUE TITLE
S3 Добавить поддержку генерации presigned URL

### ISSUE THREAD

**Issue by Daabramov** [Bayselonarrend/OpenIntegrations#46]
Хочется добавить в ПИ возможность генерации [presigned URLs](https://yandex.cloud/ru/docs/storage/concepts/pre-signed-urls) на скачивание и загрузку файлов.

**Пути решения**
Предлагается создать 2 новых метода
`- ПолучитьСсылкуДляСкачивания(Знач Наименование, Знач Бакет, Знач ОсновныеДанные, Знач ВремяЖизни, Знач Заголовки = Неопределено) ` - возвращает подписанную ссылку на скачивание файла с указанным временем жизни
`- ПолучитьСсылкуДляЗагрузки(Знач Наименование, Знач Бакет, Знач ОсновныеДанные, Знач ВремяЖизни, Знач Заголовки = Неопределено)` - возвращает подписанную ссылку на загрузку файла методом PUT и указанным временем жизни

**Comment by Bayselonarrend** [comment]
Почему бы и нет

**Comment by Bayselonarrend** [comment]
https://github.com/Bayselonarrend/OpenIntegrations/releases/tag/1.16.1

___
Если вам нравится проект, то можете поставить ⭐Спасибо)
