### ISSUE TITLE
Интеграция 1с с Телеграммом.

### ISSUE THREAD

**Issue by skuter2008** [Bayselonarrend/OpenIntegrations#49]
**Вопрос**
Здравствуйте. Установил Ваше расширение. С его помощью у меня получилось создать (Отправить) кнопки в Телеграмм, а вот нажатие на них не могу настроить. Вроде создавал и http-сервис, но не всё мне понятно. 
Я их запускал и просто из кода и из Бота 1с привязанного к Телеграмму (Интеграция стандартная).
Хочу попробовать, чтоб при отправки из Телеграмма в 1с текста создавались нужные кнопки, а при их нажатии выполнялись действия в 1с. 
Я ещё совсем плох в программировании.. новичок можно сказать..
Я скачал и установил на пробную базу вот эту доработку https://infostart.ru/marketplace/1459912/ но в ней очень много кода и всего добавляется в конфигурацию. У вас грубо говоря один модуль для общения с Телеграммом.
Будет ли у Вас возможность зайти ко мне посмотреть как можно реализовать ответ на нажатие кнопок.
В 1с с 8.3.25 уже есть встроенный механизм кнопок, но опять же он у меня только срабатывает на Боте в 1с, там приходят кнопки и выполняются нажатия на них, а вот в Телеграмм они даже не отправляются.
Буду благодарен если сможете помочь мне в этом вопросе...

**Comment by Bayselonarrend** [comment]
Здравствуйте. Можете посмотреть вот эту статью: там я описывал создание бота, в том числе и с кнопками
[https://infostart.ru/1c/articles/2135517/]

**Comment by Bayselonarrend** [comment]
Если после нее останутся вопросы, то пишите

**Comment by skuter2008** [comment]
Спасибо, что хорошо обо мне подумали:)
Имено по этой статье я все и делал.
Точнее по описаниям с создании кнопок.
Ещё точнее из Процедуры я вырезают код и вставляю его для пробы в кнопку любой формы для теста, и он у меня отправляет кнопки, а вот с функцией уже проблема её ни как не могу заставить работать..http-сервис создаю как у вас на фото , но не пойму где взять запрос и ругается на Двоичные данные...
Если бы вы смогли выделить мне хотябычасок времени был бы вам очень признателен,  потому, что что то я делаю не так и немого понять, что...
Так как сейчас внедряют к себе в 1с Телеграм и хочу по максимуму использовать все его функции...
Пока у меня он отсылает мне информацию при закрытии смены в магазине, сделал Бота в 1с и он мне присылает по запросу перечень накладных за сегодня к перемещение, и могу по запросу делать синхронизацию 
А вот с кнопками не получается

**Comment by Bayselonarrend** [comment]
Предполагаю, вам нужно внимательнее прочитать пункт про прием новых сообщений и разобраться, как работают http-серивсы

Как минмум нужно, чтобы сервис был опубликован на веб-сервере (IIS или Apache), на этом сервере должен быть SSL сертификат и доменное имя. Если это есть, то нужно вызвать `УстановитьWebhook()` на URL, по которому ваш сервис доступен. Т.е. это не будет работать, если вы просто на пустой базе создаете http-серивс и вставляете туда код из примера (тем более, что если вы вставляете функцию целиком, просто в пустой модуль, то она не будет привязана к объекту метаданных). Но публикация http-серивсов на сервере - это чисто 1Сная администраторская штука, она к работе с tg отношения не имеет

Вкратце: если вы не изучали работу с http-серивсами и их публикацию - вам сначала надо разобраться с основами. Если уже все, что описано выше, есть, то нужно отладчиком смотреть, что возвращает Telegram. Если поднять сервер и SSL возможности нет, то можете рассмотреть Polling вариант - он в статье тоже описан

**Comment by skuter2008** [comment]
Может у Вас появиться часок другой времени, чтоб доработать мою 1с для общения с Телеграммом. 
Потому, что мои программисты которые сопровождают мою 1с по ККТ они не сталкивались с Интеграцией Телеграмма, я с ними посидел поразбирался, точнее мы вместе, за мой счёт, посидели по изучали мануал из 1с к Телеграмму и не смогли нечего сделать. Вот пробую сам, но если бы у вас получилось мне помочь было бы хорошо. У меня был хороший программист, даже очень хороший с Украины, но после февраля 2022г, он не может мне помогать в реализации моих хотелок в 1с .....
У меня база опубликована на сервере IIS ,  публикую и новый (созданный) http-сервис , но у меня нет знаний, чтоб всё это свести в одну кучу.....

**Comment by Bayselonarrend** [comment]
Слушайте, я не хочу вас обидеть и пытаюсь войти в положение, но давайте поговорим серьезно - я занимаю поддержкой библиотеки: чиню проблемные места, отвечаю на конкретные вопросы о ее работе и, в частности, добавляю новый функционал, если кому-то чего-то не хватает. Но я не занимаюсь внедрением или поддержкой на конкретных базах - для этой работы существуют франчи и биржи фрилансеров

Что касается вашей ситуации, то проблема непонимания чего-то вашими программистами, видимо, не связана с интеграцией телеграма. Все, что нужно для отлова событий - http-сервис, опубликованный на сервере с SSL. Это не связано с телеграмом и обеспечение этого - работа системного администратора, а не программиста. Если же у вас есть такой сервис, доступный по адресу типа `https://вашдомен.ru/base/hs/telegram`, то дальше идет абсолютно базовое, начального уровня программирование - просто нужно вызывать методы. [Вот документация](https://openintegrations.dev/), где подробно с примерами расписаны все доступные функции и плюс статья, которую я скидывал ранее. 

Просто в итоге мы попадаем в такую ситуацию, где либо у вас нет настроенной публицаии сервиса с сертификатом - и я даже при всем желании вам с этим не могу помочь, либо программисты не знают как через 3 кнопки создать обработчик сервиса - это, конечно, очень странно, но в любом случае, о какой интеграции идет речь - вы просто застопоритесь опять где-то чуть дальше

Этот проект расчитан как "от программистов программистам". Если у вас появятся какие-нибудь **конкретные** технические вопросы про функции, которые есть в библиотеке или как они работают, то я с радостью на них отвечу

**Comment by skuter2008** [comment]
Понял Вас, мой вопрос не Вашего уровня. 
Но всё равно Спасибо Вам за уделённое время и за такие публикации!
